name: Backend CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Environment Variables
      run: | 
        echo "EHAYVAN_SPRING_DATASOURCE_URL=${{ secrets.EHAYVAN_SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
        echo "EHAYVAN_SPRING_DATASOURCE_USERNAME=${{ secrets.EHAYVAN_SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
        echo "EHAYVAN_SPRING_DATASOURCE_PASSWORD=${{ secrets.EHAYVAN_SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
        echo "EHAYVAN_SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.EHAYVAN_SPRING_DATASOURCE_DRIVER_CLASS_NAME }}" >> $GITHUB_ENV
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and test
      run: mvn clean install -DskipTests
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml
