name: Backend CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '21'
    - name: Build and test
      run: mvn clean install
